;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Skill.AddExp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill.LevelUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill.Sacrifice",DevComment="")
+GameplayTagList=(Tag="GAS.Effect.DropExp",DevComment="")
+GameplayTagList=(Tag="GAS.Effect.Sacrifice",DevComment="")

